spring.application.name=currency-conversion-service

server.port=8100
spring.config.import=optional:configserver:http://localhost:8888

spring.datasource.url=jdbc:postgresql://localhost:5432/restwebDB
spring.datasource.username =postgres
spring.datasource.password =postgres

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka

eureka.instance.hostname=localhost